import { motion } from "motion/react";
import {
  CheckCircle2,
  GitCommitHorizontal,
  RefreshCw,
  Sparkles,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { cn } from "@/lib/utils";
import type { Meeting } from "@/types";

export function SummaryView({
  meeting,
  onRegenerate,
  regenerating,
  canSummarize = true,
}: {
  meeting: Meeting;
  onRegenerate: () => void;
  regenerating: boolean;
  /** False when there's no transcript to summarize (e.g. no audio captured). */
  canSummarize?: boolean;
}) {
  const summary = meeting.summary;
  const pending = meeting.status === "live" || meeting.status === "processing";

  if (!summary) {
    return (
      <div className="rounded-xl border border-dashed border-border bg-card/50 p-6">
        {pending ? (
          <div className="space-y-3">
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <Sparkles className="size-4 animate-pulse text-primary" />
              Generating summary once the meeting ends…
            </div>
            <Skeleton className="h-3 w-full" />
            <Skeleton className="h-3 w-11/12" />
            <Skeleton className="h-3 w-4/5" />
          </div>
        ) : (
          <div className="flex flex-col items-center gap-3 py-4 text-center">
            <Sparkles className="size-6 text-primary" />
            <p className="text-sm text-muted-foreground">
              {canSummarize
                ? "No summary yet for this meeting."
                : "Transcribe the recording first — there's no transcript to summarize yet."}
            </p>
            <Button
              variant="brand"
              size="sm"
              onClick={onRegenerate}
              disabled={!canSummarize}
            >
              <Sparkles /> Generate summary
            </Button>
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="space-y-5">
      {/* TL;DR */}
      <motion.div
        initial={{ opacity: 0, y: 6 }}
        animate={{ opacity: 1, y: 0 }}
        className="rounded-xl border border-primary/20 bg-gradient-to-br from-accent/60 to-transparent p-4"
      >
        <div className="mb-2 flex items-center justify-between">
          <div className="flex items-center gap-2 text-sm font-semibold text-primary">
            <Sparkles className="size-4" />
            AI Summary
          </div>
          <Button
            variant="ghost"
            size="sm"
            onClick={onRegenerate}
            disabled={regenerating || !canSummarize}
            className="h-7 text-xs text-muted-foreground"
          >
            <RefreshCw className={cn("size-3.5", regenerating && "animate-spin")} />
            Regenerate
          </Button>
        </div>
        <p className="selectable text-sm leading-relaxed text-foreground/90">
          {summary.tldr}
        </p>
      </motion.div>

      {summary.keyPoints.length > 0 && (
        <Section title="Key points" icon={<CheckCircle2 className="size-4" />}>
          <ul className="space-y-2">
            {summary.keyPoints.map((point, i) => (
              <li key={i} className="flex gap-2.5 text-sm">
                <span className="mt-2 size-1.5 shrink-0 rounded-full bg-primary" />
                <span className="selectable leading-relaxed text-foreground/90">
                  {point}
                </span>
              </li>
            ))}
          </ul>
        </Section>
      )}

      {summary.decisions.length > 0 && (
        <Section
          title="Decisions"
          icon={<GitCommitHorizontal className="size-4" />}
        >
          <ul className="space-y-2">
            {summary.decisions.map((d, i) => (
              <li
                key={i}
                className="flex items-center gap-2.5 rounded-lg border border-border bg-card px-3 py-2 text-sm"
              >
                <CheckCircle2 className="size-4 shrink-0 text-success" />
                <span className="selectable text-foreground/90">{d}</span>
              </li>
            ))}
          </ul>
        </Section>
      )}

      <p className="text-xs text-muted-foreground">
        Generated by {summary.model} ·{" "}
        {new Date(summary.generatedAt).toLocaleString()}
      </p>
    </div>
  );
}

function Section({
  title,
  icon,
  children,
}: {
  title: string;
  icon: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <div>
      <h3 className="mb-2.5 flex items-center gap-2 text-sm font-semibold text-foreground">
        <span className="text-muted-foreground">{icon}</span>
        {title}
      </h3>
      {children}
    </div>
  );
}
